name: Night Light ğŸ’¡

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (UTC)
  workflow_dispatch:        # Allows manual trigger

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
      - name: Ping my portolio_3 ğŸ™â€â™‚ï¸
        run: curl -s https://portfolio-4n0j.onrender.com

      - name: Ping ME application ğŸ“‰
        run: curl -s https://me-ne9o.onrender.com